# Generated by Django 6.0 on 2025-12-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergarten',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='max_age',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='min_age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
