# Generated by Django 5.2.8 on 2025-12-11 11:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kindergarten_district_kindergarten_max_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Ребенок', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Запись в группу', 'verbose_name_plural': 'Записи в группы'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['kindergarten', 'name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='kindergarten',
            options={'ordering': ['name'], 'verbose_name': 'Детский сад', 'verbose_name_plural': 'Детские сады'},
        ),
        migrations.AlterModelOptions(
            name='kindergartenteacher',
            options={'verbose_name': 'Работа воспитателя в саду', 'verbose_name_plural': 'Работы воспитателей в садах'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Воспитатель', 'verbose_name_plural': 'Воспитатели'},
        ),
        migrations.RemoveField(
            model_name='kindergarten',
            name='district',
        ),
        migrations.RemoveField(
            model_name='kindergarten',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='kindergarten',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='kindergarten',
            name='specialization',
        ),
        migrations.AddField(
            model_name='group',
            name='max_capacity',
            field=models.IntegerField(default=15, verbose_name='Максимальная вместимость'),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='features',
            field=models.TextField(blank=True, help_text='Каждая особенность с новой строки', verbose_name='Особенности'),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AddField(
            model_name='kindergartenteacher',
            name='role',
            field=models.CharField(choices=[('воспитатель', 'Воспитатель'), ('старший', 'Старший воспитатель'), ('методист', 'Методист'), ('заведующий', 'Заведующий'), ('психолог', 'Психолог'), ('логопед', 'Логопед')], default='воспитатель', max_length=50, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='kindergartenteacher',
            name='years_at_kindergarten',
            field=models.IntegerField(default=0, verbose_name='Стаж в этом саду (лет)'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email родителя'),
        ),
        migrations.AddField(
            model_name='review',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон родителя'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='Стаж (лет)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent_contact',
            field=models.CharField(max_length=100, verbose_name='Контакты родителей'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.child', verbose_name='Ребенок'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('активна', 'Активна'), ('ожидание', 'В ожидании'), ('отклонена', 'Отклонена'), ('завершена', 'Завершена')], default='ожидание', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='group',
            name='age_range',
            field=models.CharField(max_length=50, verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='established_at',
            field=models.DateField(verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default=1, verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='parent_name',
            field=models.CharField(max_length=100, verbose_name='Имя родителя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(choices=[('высшая', 'Высшая категория'), ('первая', 'Первая категория'), ('вторая', 'Вторая категория'), ('без', 'Без категории'), ('молодой', 'Молодой специалист')], max_length=50, verbose_name='Квалификация'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('child', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='kindergartenteacher',
            unique_together={('teacher', 'kindergarten')},
        ),
        migrations.CreateModel(
            name='KindergartenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kindergartens/images/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.kindergarten')),
            ],
            options={
                'verbose_name': 'Фотография детского сада',
                'verbose_name_plural': 'Фотографии детских садов',
                'ordering': ['order'],
            },
        ),
    ]
