# Generated by Django 5.2.8 on 2025-12-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_child_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindergartenimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='kindergartenimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='kindergartenimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kindergartenimage',
            name='order',
        ),
    ]
