# Generated by Django 5.2.8 on 2025-12-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_kindergartenimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergartenimage',
            name='kindergarten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kindergarten'),
        ),
    ]
