# Generated by Django 5.2.8 on 2025-12-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_kindergartenimage_kindergarten'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergartenimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
