# Generated by Django 5.2.7 on 2025-10-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('capacity', models.IntegerField(default=0, verbose_name='Вместимость (детей)')),
                ('age_group', models.CharField(choices=[('1.5-3', '1.5–3 года'), ('3-7', '3–7 лет'), ('1.5-7', '1.5–7 лет')], max_length=50, verbose_name='Возрастная группа')),
                ('work_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Режим работы')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='kindergartens/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Детский сад',
                'verbose_name_plural': 'Детские сады',
            },
        ),
    ]
