# Generated by Django 5.2.7 on 2025-10-23 19:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standoff2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('parent_contact', models.CharField(max_length=255, verbose_name='Контакт родителя')),
            ],
            options={
                'verbose_name': 'Ребёнок',
                'verbose_name_plural': 'Дети',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('qualification', models.CharField(max_length=255, verbose_name='Квалификация')),
            ],
            options={
                'verbose_name': 'Воспитатель',
                'verbose_name_plural': 'Воспитатели',
            },
        ),
        migrations.RemoveField(
            model_name='kindergarten',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='kindergarten',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kindergarten',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='kindergarten',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='established_at',
            field=models.DateField(default=datetime.date(2020, 1, 1), verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='capacity',
            field=models.IntegerField(verbose_name='Вместимость (кол-во детей)'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('age_range', models.CharField(max_length=50, verbose_name='Возрастная категория')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standoff2.kindergarten', verbose_name='Детский сад')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Дата зачисления')),
                ('status', models.CharField(max_length=255, verbose_name='Статус зачисления')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standoff2.child', verbose_name='Ребёнок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standoff2.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Зачисление',
                'verbose_name_plural': 'Зачисления',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=255, verbose_name='Имя родителя')),
                ('rating', models.IntegerField(verbose_name='Оценка (1–5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standoff2.kindergarten', verbose_name='Детский сад')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='KindergartenTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standoff2.kindergarten', verbose_name='Детский сад')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standoff2.teacher', verbose_name='Воспитатель')),
            ],
            options={
                'verbose_name': 'Связь детский сад–воспитатель',
                'verbose_name_plural': 'Связи детский сад–воспитатель',
            },
        ),
    ]
